// packages/react/lib/GcdsTableWithSlots.tsx
// GcdsTable.tsx
import React, { useMemo } from 'react';
import { GcdsTable as GcdsTableBase } from './components';
import type { TableColumn } from '@gcds-core/components';

type CellRenderer<T> = (props: CellSlotProps<T>) => React.ReactNode;
export interface ReactTableColumn<T = Record<string, unknown>>
  extends TableColumn {
  renderCell?: CellRenderer<T>;
}

export interface CellSlotProps<T = Record<string, unknown>> {
  row: T;
  rowIndex: number;
  column: ReactTableColumn<T>;
  value: unknown;
}

export interface GcdsTableProps extends React.HTMLAttributes<HTMLElement> {
  columns?: ReactTableColumn[];
  data?: Record<string, unknown>[];
  filter?: boolean;
  filterValue?: string;
  pagination?: boolean;
  paginationCurrentPage?: number;
  paginationSize?: number;
  paginationSizeOptions?: number[];
  sort?: boolean;
  captionSlot?: React.ReactNode;
  children?: React.ReactNode;
}

function getCellValue(row: Record<string, unknown>, field: string): unknown {
  return row?.[field];
}

function getRowKey(row: Record<string, unknown>, rowIndex: number): string {
  const candidate = row?.['id'];
  if (candidate === null || candidate === undefined || candidate === '') {
    return String(rowIndex);
  }
  return String(candidate);
}

function getSlotName(
  row: Record<string, unknown>,
  column: ReactTableColumn,
  rowIndex: number,
): string {
  return `cell-${getRowKey(row, rowIndex)}-${column.field}`;
}

export function GcdsTableWithSlots({
  columns = [],
  data = [],
  filter = false,
  filterValue = '',
  pagination = false,
  paginationCurrentPage = 1,
  paginationSize = 10,
  paginationSizeOptions = [10, 25, 50, 0],
  sort = false,
  children,
  ...rest
}: GcdsTableProps) {
  const wcColumns = useMemo(() =>
    columns.map(({ renderCell, ...col }) => ({
      ...col,
      managed: renderCell ? true : undefined,
    })),
    [columns]
  );

  const columnSlots = useMemo(() =>
    data.flatMap((row, rowIndex) =>
      columns
        .filter(col => !!col.renderCell)
        .map(col => (
          <span
            key={getSlotName(row, col, rowIndex)}
            slot={getSlotName(row, col, rowIndex)}
          >
            {col.renderCell?.({
              row,
              rowIndex,
              column: col,
              value: getCellValue(row, col.field),
            })}
          </span>
        ))
    ),
    [data, columns]
  );

  return (
    <GcdsTableBase
      {...rest}
      columns={wcColumns}
      data={data}
      filter={filter}
      filterValue={filterValue}
      pagination={pagination}
      paginationCurrentPage={paginationCurrentPage}
      paginationSize={paginationSize}
      paginationSizeOptions={paginationSizeOptions}
      sort={sort}
    >
      {children}
      {columnSlots}
    </GcdsTableBase>
  );
}

// packages/angular/src/lib/gcds-table-with-slots.component.ts
import {
  Component,
  Input,
  TemplateRef,
  QueryList,
  ContentChildren,
  AfterContentInit,
  OnChanges,
} from '@angular/core';
import type { TableColumn } from '@gcds-core/components';
import { GcdsCellDirective } from './directives/gcds-cell.directive';

export interface AngularTableColumn extends TableColumn {
  cellTemplate?: TemplateRef<{ $implicit: unknown; rowId: string }>;
}

@Component({
  selector: 'gcds-table-ng',
  standalone: false,
  template: `
    <gcds-table
      [columns]="wcColumns"
      [data]="data"
      [filter]="filter"
      [filterValue]="filterValue"
      [pagination]="pagination"
      [paginationCurrentPage]="paginationCurrentPage"
      [paginationSize]="paginationSize"
      [paginationSizeOptions]="paginationSizeOptions"
      [sort]="sort"
    >
      <ng-content select="[slot='caption']"></ng-content>

      <ng-container *ngFor="let row of data; let rowIndex = index">
        <ng-container *ngFor="let column of columns">
          <span
            *ngIf="getTemplate(column.field) as template"
            [attr.slot]="getSlotName(row, column, rowIndex)"
          >
            <ng-container
              [ngTemplateOutlet]="template"
              [ngTemplateOutletContext]="{
                $implicit: row,
                row: row,
                rowIndex: rowIndex,
                column: column,
                value: getCellValue(row, column.field),
              }"
            ></ng-container>
          </span>
        </ng-container>
      </ng-container>

      <ng-content></ng-content>
    </gcds-table>
  `,
})
export class GcdsTableWithSlotsComponent
  implements AfterContentInit, OnChanges
{
  @Input() columns: AngularTableColumn[] = [];
  @Input() data: Record<string, unknown>[] = [];
  @Input() filter = false;
  @Input() filterValue = '';
  @Input() pagination = false;
  @Input() paginationCurrentPage = 1;
  @Input() paginationSize = 10;
  @Input() paginationSizeOptions: number[] = [10, 25, 50, 0];
  @Input() sort = false;

  @ContentChildren(GcdsCellDirective)
  cellTemplates!: QueryList<GcdsCellDirective>;

  private _wcColumns: TableColumn[] = [];

  get wcColumns(): TableColumn[] {
    return this._wcColumns;
  }

  ngAfterContentInit(): void {
    this._wcColumns = this.computeWcColumns();

    this.cellTemplates.changes.subscribe(() => {
      this._wcColumns = this.computeWcColumns();
    });
  }

  ngOnChanges(): void {
    if (this.cellTemplates) {
      this._wcColumns = this.computeWcColumns();
    }
  }

  private computeWcColumns(): TableColumn[] {
    const templateMap = new Map(
      this.cellTemplates.map(d => [d.field, d.template]),
    );

    return this.columns.map(col => ({
      ...col,
      managed: templateMap.has(col.field) ? true : undefined,
    }));
  }

  get slottedColumns(): { field: string; template: TemplateRef<any> }[] {
    return this.cellTemplates.map(d => ({
      field: d.field,
      template: d.template,
    }));
  }

  private get templateMap(): Map<string, TemplateRef<any>> {
    return new Map(this.cellTemplates.map(d => [d.field, d.template]));
  }

  getTemplate(field: string): TemplateRef<any> | null {
    return this.templateMap.get(field) ?? null;
  }

  getCellValue(row: Record<string, unknown>, field: string): unknown {
    return row?.[field as keyof typeof row];
  }

  getRowKey(row: Record<string, unknown>, rowIndex: number): string {
    const candidate = row?.['id'];

    if (candidate === null || candidate === undefined || candidate === '') {
      return String(rowIndex);
    }

    return String(candidate);
  }

  getSlotName(
    row: Record<string, unknown>,
    column: AngularTableColumn,
    rowIndex: number,
  ): string {
    return `cell-${this.getRowKey(row, rowIndex)}-${column.field}`;
  }
}
